### ISSUE TITLE
znc-certinfo fails to build on FreeBSD

### ISSUE THREAD

**Issue by spitfire** [Codeux-Software/znc-certinfo#1]
OS: FreeBSD 9.3-RELEASE-p28 #0 r288272+4d913dc
package: znc-1.6.1_1
# /usr/local/bin/znc-buildmod certinfo.cpp

Building "certinfo.so" for ZNC 1.6.1... certinfo.cpp: In member function 'void CCertInfoMod::SendCertificateCommand(const CString&)':
certinfo.cpp:98:29: error: 'class CIRCSock' has no member named 'GetSSLObject'
   SSL *sslContext = socket->GetSSLObject();
                             ^
[ !! ] Error while building "certinfo.so"

**Comment by emsquared** [comment]
GetSSLObject is [defined in the header file for Csocket](https://github.com/jimloco/Csocket/blob/master/Csocket.h#L884) which ZNC inherits from.

If its failing to find the object, then it the declaration may have been recently added (the module was built against git version of ZNC) or you are not b building with SSL enabled (HAVE_LIBSSL define).
